# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/jacopoclocchiatti/Documents/Uni/UniTn-local/HPC/Parallel_A_Star

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/jacopoclocchiatti/Documents/Uni/UniTn-local/HPC/Parallel_A_Star

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jacopoclocchiatti/Documents/Uni/UniTn-local/HPC/Parallel_A_Star/CMakeFiles /Users/jacopoclocchiatti/Documents/Uni/UniTn-local/HPC/Parallel_A_Star//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jacopoclocchiatti/Documents/Uni/UniTn-local/HPC/Parallel_A_Star/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named parallel_a_star_new

# Build rule for target.
parallel_a_star_new: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 parallel_a_star_new
.PHONY : parallel_a_star_new

# fast build rule for target.
parallel_a_star_new/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parallel_a_star_new.dir/build.make CMakeFiles/parallel_a_star_new.dir/build
.PHONY : parallel_a_star_new/fast

src/adjlist.o: src/adjlist.c.o
.PHONY : src/adjlist.o

# target to build an object file
src/adjlist.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parallel_a_star_new.dir/build.make CMakeFiles/parallel_a_star_new.dir/src/adjlist.c.o
.PHONY : src/adjlist.c.o

src/adjlist.i: src/adjlist.c.i
.PHONY : src/adjlist.i

# target to preprocess a source file
src/adjlist.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parallel_a_star_new.dir/build.make CMakeFiles/parallel_a_star_new.dir/src/adjlist.c.i
.PHONY : src/adjlist.c.i

src/adjlist.s: src/adjlist.c.s
.PHONY : src/adjlist.s

# target to generate assembly for a file
src/adjlist.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parallel_a_star_new.dir/build.make CMakeFiles/parallel_a_star_new.dir/src/adjlist.c.s
.PHONY : src/adjlist.c.s

src/cJSON.o: src/cJSON.c.o
.PHONY : src/cJSON.o

# target to build an object file
src/cJSON.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parallel_a_star_new.dir/build.make CMakeFiles/parallel_a_star_new.dir/src/cJSON.c.o
.PHONY : src/cJSON.c.o

src/cJSON.i: src/cJSON.c.i
.PHONY : src/cJSON.i

# target to preprocess a source file
src/cJSON.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parallel_a_star_new.dir/build.make CMakeFiles/parallel_a_star_new.dir/src/cJSON.c.i
.PHONY : src/cJSON.c.i

src/cJSON.s: src/cJSON.c.s
.PHONY : src/cJSON.s

# target to generate assembly for a file
src/cJSON.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parallel_a_star_new.dir/build.make CMakeFiles/parallel_a_star_new.dir/src/cJSON.c.s
.PHONY : src/cJSON.c.s

src/comm.o: src/comm.c.o
.PHONY : src/comm.o

# target to build an object file
src/comm.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parallel_a_star_new.dir/build.make CMakeFiles/parallel_a_star_new.dir/src/comm.c.o
.PHONY : src/comm.c.o

src/comm.i: src/comm.c.i
.PHONY : src/comm.i

# target to preprocess a source file
src/comm.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parallel_a_star_new.dir/build.make CMakeFiles/parallel_a_star_new.dir/src/comm.c.i
.PHONY : src/comm.c.i

src/comm.s: src/comm.c.s
.PHONY : src/comm.s

# target to generate assembly for a file
src/comm.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parallel_a_star_new.dir/build.make CMakeFiles/parallel_a_star_new.dir/src/comm.c.s
.PHONY : src/comm.c.s

src/compute_distance.o: src/compute_distance.c.o
.PHONY : src/compute_distance.o

# target to build an object file
src/compute_distance.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parallel_a_star_new.dir/build.make CMakeFiles/parallel_a_star_new.dir/src/compute_distance.c.o
.PHONY : src/compute_distance.c.o

src/compute_distance.i: src/compute_distance.c.i
.PHONY : src/compute_distance.i

# target to preprocess a source file
src/compute_distance.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parallel_a_star_new.dir/build.make CMakeFiles/parallel_a_star_new.dir/src/compute_distance.c.i
.PHONY : src/compute_distance.c.i

src/compute_distance.s: src/compute_distance.c.s
.PHONY : src/compute_distance.s

# target to generate assembly for a file
src/compute_distance.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parallel_a_star_new.dir/build.make CMakeFiles/parallel_a_star_new.dir/src/compute_distance.c.s
.PHONY : src/compute_distance.c.s

src/compute_path.o: src/compute_path.c.o
.PHONY : src/compute_path.o

# target to build an object file
src/compute_path.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parallel_a_star_new.dir/build.make CMakeFiles/parallel_a_star_new.dir/src/compute_path.c.o
.PHONY : src/compute_path.c.o

src/compute_path.i: src/compute_path.c.i
.PHONY : src/compute_path.i

# target to preprocess a source file
src/compute_path.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parallel_a_star_new.dir/build.make CMakeFiles/parallel_a_star_new.dir/src/compute_path.c.i
.PHONY : src/compute_path.c.i

src/compute_path.s: src/compute_path.c.s
.PHONY : src/compute_path.s

# target to generate assembly for a file
src/compute_path.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parallel_a_star_new.dir/build.make CMakeFiles/parallel_a_star_new.dir/src/compute_path.c.s
.PHONY : src/compute_path.c.s

src/exit_points.o: src/exit_points.c.o
.PHONY : src/exit_points.o

# target to build an object file
src/exit_points.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parallel_a_star_new.dir/build.make CMakeFiles/parallel_a_star_new.dir/src/exit_points.c.o
.PHONY : src/exit_points.c.o

src/exit_points.i: src/exit_points.c.i
.PHONY : src/exit_points.i

# target to preprocess a source file
src/exit_points.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parallel_a_star_new.dir/build.make CMakeFiles/parallel_a_star_new.dir/src/exit_points.c.i
.PHONY : src/exit_points.c.i

src/exit_points.s: src/exit_points.c.s
.PHONY : src/exit_points.s

# target to generate assembly for a file
src/exit_points.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parallel_a_star_new.dir/build.make CMakeFiles/parallel_a_star_new.dir/src/exit_points.c.s
.PHONY : src/exit_points.c.s

src/json_output.o: src/json_output.c.o
.PHONY : src/json_output.o

# target to build an object file
src/json_output.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parallel_a_star_new.dir/build.make CMakeFiles/parallel_a_star_new.dir/src/json_output.c.o
.PHONY : src/json_output.c.o

src/json_output.i: src/json_output.c.i
.PHONY : src/json_output.i

# target to preprocess a source file
src/json_output.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parallel_a_star_new.dir/build.make CMakeFiles/parallel_a_star_new.dir/src/json_output.c.i
.PHONY : src/json_output.c.i

src/json_output.s: src/json_output.c.s
.PHONY : src/json_output.s

# target to generate assembly for a file
src/json_output.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parallel_a_star_new.dir/build.make CMakeFiles/parallel_a_star_new.dir/src/json_output.c.s
.PHONY : src/json_output.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parallel_a_star_new.dir/build.make CMakeFiles/parallel_a_star_new.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parallel_a_star_new.dir/build.make CMakeFiles/parallel_a_star_new.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parallel_a_star_new.dir/build.make CMakeFiles/parallel_a_star_new.dir/src/main.c.s
.PHONY : src/main.c.s

src/parallel.o: src/parallel.c.o
.PHONY : src/parallel.o

# target to build an object file
src/parallel.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parallel_a_star_new.dir/build.make CMakeFiles/parallel_a_star_new.dir/src/parallel.c.o
.PHONY : src/parallel.c.o

src/parallel.i: src/parallel.c.i
.PHONY : src/parallel.i

# target to preprocess a source file
src/parallel.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parallel_a_star_new.dir/build.make CMakeFiles/parallel_a_star_new.dir/src/parallel.c.i
.PHONY : src/parallel.c.i

src/parallel.s: src/parallel.c.s
.PHONY : src/parallel.s

# target to generate assembly for a file
src/parallel.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parallel_a_star_new.dir/build.make CMakeFiles/parallel_a_star_new.dir/src/parallel.c.s
.PHONY : src/parallel.c.s

src/parallel_collection.o: src/parallel_collection.c.o
.PHONY : src/parallel_collection.o

# target to build an object file
src/parallel_collection.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parallel_a_star_new.dir/build.make CMakeFiles/parallel_a_star_new.dir/src/parallel_collection.c.o
.PHONY : src/parallel_collection.c.o

src/parallel_collection.i: src/parallel_collection.c.i
.PHONY : src/parallel_collection.i

# target to preprocess a source file
src/parallel_collection.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parallel_a_star_new.dir/build.make CMakeFiles/parallel_a_star_new.dir/src/parallel_collection.c.i
.PHONY : src/parallel_collection.c.i

src/parallel_collection.s: src/parallel_collection.c.s
.PHONY : src/parallel_collection.s

# target to generate assembly for a file
src/parallel_collection.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parallel_a_star_new.dir/build.make CMakeFiles/parallel_a_star_new.dir/src/parallel_collection.c.s
.PHONY : src/parallel_collection.c.s

src/parallel_distribution.o: src/parallel_distribution.c.o
.PHONY : src/parallel_distribution.o

# target to build an object file
src/parallel_distribution.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parallel_a_star_new.dir/build.make CMakeFiles/parallel_a_star_new.dir/src/parallel_distribution.c.o
.PHONY : src/parallel_distribution.c.o

src/parallel_distribution.i: src/parallel_distribution.c.i
.PHONY : src/parallel_distribution.i

# target to preprocess a source file
src/parallel_distribution.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parallel_a_star_new.dir/build.make CMakeFiles/parallel_a_star_new.dir/src/parallel_distribution.c.i
.PHONY : src/parallel_distribution.c.i

src/parallel_distribution.s: src/parallel_distribution.c.s
.PHONY : src/parallel_distribution.s

# target to generate assembly for a file
src/parallel_distribution.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parallel_a_star_new.dir/build.make CMakeFiles/parallel_a_star_new.dir/src/parallel_distribution.c.s
.PHONY : src/parallel_distribution.c.s

src/parallel_paths.o: src/parallel_paths.c.o
.PHONY : src/parallel_paths.o

# target to build an object file
src/parallel_paths.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parallel_a_star_new.dir/build.make CMakeFiles/parallel_a_star_new.dir/src/parallel_paths.c.o
.PHONY : src/parallel_paths.c.o

src/parallel_paths.i: src/parallel_paths.c.i
.PHONY : src/parallel_paths.i

# target to preprocess a source file
src/parallel_paths.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parallel_a_star_new.dir/build.make CMakeFiles/parallel_a_star_new.dir/src/parallel_paths.c.i
.PHONY : src/parallel_paths.c.i

src/parallel_paths.s: src/parallel_paths.c.s
.PHONY : src/parallel_paths.s

# target to generate assembly for a file
src/parallel_paths.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parallel_a_star_new.dir/build.make CMakeFiles/parallel_a_star_new.dir/src/parallel_paths.c.s
.PHONY : src/parallel_paths.c.s

src/print.o: src/print.c.o
.PHONY : src/print.o

# target to build an object file
src/print.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parallel_a_star_new.dir/build.make CMakeFiles/parallel_a_star_new.dir/src/print.c.o
.PHONY : src/print.c.o

src/print.i: src/print.c.i
.PHONY : src/print.i

# target to preprocess a source file
src/print.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parallel_a_star_new.dir/build.make CMakeFiles/parallel_a_star_new.dir/src/print.c.i
.PHONY : src/print.c.i

src/print.s: src/print.c.s
.PHONY : src/print.s

# target to generate assembly for a file
src/print.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parallel_a_star_new.dir/build.make CMakeFiles/parallel_a_star_new.dir/src/print.c.s
.PHONY : src/print.c.s

src/priority_queue.o: src/priority_queue.c.o
.PHONY : src/priority_queue.o

# target to build an object file
src/priority_queue.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parallel_a_star_new.dir/build.make CMakeFiles/parallel_a_star_new.dir/src/priority_queue.c.o
.PHONY : src/priority_queue.c.o

src/priority_queue.i: src/priority_queue.c.i
.PHONY : src/priority_queue.i

# target to preprocess a source file
src/priority_queue.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parallel_a_star_new.dir/build.make CMakeFiles/parallel_a_star_new.dir/src/priority_queue.c.i
.PHONY : src/priority_queue.c.i

src/priority_queue.s: src/priority_queue.c.s
.PHONY : src/priority_queue.s

# target to generate assembly for a file
src/priority_queue.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parallel_a_star_new.dir/build.make CMakeFiles/parallel_a_star_new.dir/src/priority_queue.c.s
.PHONY : src/priority_queue.c.s

src/utility.o: src/utility.c.o
.PHONY : src/utility.o

# target to build an object file
src/utility.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parallel_a_star_new.dir/build.make CMakeFiles/parallel_a_star_new.dir/src/utility.c.o
.PHONY : src/utility.c.o

src/utility.i: src/utility.c.i
.PHONY : src/utility.i

# target to preprocess a source file
src/utility.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parallel_a_star_new.dir/build.make CMakeFiles/parallel_a_star_new.dir/src/utility.c.i
.PHONY : src/utility.c.i

src/utility.s: src/utility.c.s
.PHONY : src/utility.s

# target to generate assembly for a file
src/utility.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parallel_a_star_new.dir/build.make CMakeFiles/parallel_a_star_new.dir/src/utility.c.s
.PHONY : src/utility.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... parallel_a_star_new"
	@echo "... src/adjlist.o"
	@echo "... src/adjlist.i"
	@echo "... src/adjlist.s"
	@echo "... src/cJSON.o"
	@echo "... src/cJSON.i"
	@echo "... src/cJSON.s"
	@echo "... src/comm.o"
	@echo "... src/comm.i"
	@echo "... src/comm.s"
	@echo "... src/compute_distance.o"
	@echo "... src/compute_distance.i"
	@echo "... src/compute_distance.s"
	@echo "... src/compute_path.o"
	@echo "... src/compute_path.i"
	@echo "... src/compute_path.s"
	@echo "... src/exit_points.o"
	@echo "... src/exit_points.i"
	@echo "... src/exit_points.s"
	@echo "... src/json_output.o"
	@echo "... src/json_output.i"
	@echo "... src/json_output.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/parallel.o"
	@echo "... src/parallel.i"
	@echo "... src/parallel.s"
	@echo "... src/parallel_collection.o"
	@echo "... src/parallel_collection.i"
	@echo "... src/parallel_collection.s"
	@echo "... src/parallel_distribution.o"
	@echo "... src/parallel_distribution.i"
	@echo "... src/parallel_distribution.s"
	@echo "... src/parallel_paths.o"
	@echo "... src/parallel_paths.i"
	@echo "... src/parallel_paths.s"
	@echo "... src/print.o"
	@echo "... src/print.i"
	@echo "... src/print.s"
	@echo "... src/priority_queue.o"
	@echo "... src/priority_queue.i"
	@echo "... src/priority_queue.s"
	@echo "... src/utility.o"
	@echo "... src/utility.i"
	@echo "... src/utility.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

